version: "2"
formatters:
  enable:
    - gofmt
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/sgnl-ai)
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

linters:
  default: none
  enable:
    - asciicheck
    - decorder
    - dupl
    - dupword
    - durationcheck
    - forcetypeassert
    - goconst
    - gocritic
    - godot
    - goheader
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - nlreturn
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - wsl
  exclusions:
    generated: lax
    rules:
      - path: (.+)_test.go
        linters:
          - dupl
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    nestif:
      min-complexity: 10
    gocritic:
      disable-all: true
      enabled-checks:
        - dupImport
    goheader:
      values:
        const:
          COMPANY: SGNL.ai, Inc.
      template: Copyright {{ YEAR }} {{ COMPANY }}
